environments:
  default:
    values:
    - jx-values.yaml
releases:
- chart: '../{{ requiredEnv "APP_NAME" }}'
  name: preview
  wait: true
  createNamespace: true
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
  - jx-values.yaml
  - values.yaml.gotmpl
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "jx"
    args:
      - secret
      - copy
      - --create-namespace
      - --selector
      - "secret.jenkins-x.io/replica-source=true"
      - --to
      - '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
